### ISSUE TITLE
Is not return a body when the response is an instance of HttpErrorResponse

### ISSUE THREAD

**Issue by JulioWar** [troyanskiy/ngx-resource-handler-ngx-http#5]
Hello @troyanskiy.

I can see in [here](https://github.com/troyanskiy/ngx-resource-handler-ngx-http/blob/4a7fdf86fac2b4a011e5d2cfd6d966073364d444/src/ResourceHandlerHttpClient.ts#L100) that you are handle all the response there but when things when is an response from error the response doesn't have the body property, instead HttpClient return an property error that replace the body as you can see here: 

![captura-code](https://user-images.githubusercontent.com/6256473/34019513-fcc05754-e0f4-11e7-8523-3a31fb687186.PNG)

My proposal is this:
```typescript
protected handleResponse(req: IResourceRequest, response: HttpResponse<any>): IResourceResponse {
    const headers: any = {};
    const body: any = response.body;
    const keys = response.headers.keys();
    keys.forEach((key: string) => {
      headers[key] = response.headers.getAll(key);
    });

    if (response instanceof HttpErrorResponse) {
      body = response.error;
    }

    return {
      status: response.status,
      body: body,
      headers: headers
    };
  }
```

You can check if is an instance of HttpErrorResponse or if the body  doesn't exist.

**Comment by troyanskiy** [comment]
Thanks for the issue and the proposition of fix.
I will implement that right now.

**Comment by JulioWar** [comment]
Thanks, Your solution is more clean 👌.
